remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Data Analytics Portfolio - May]
description: [Welcome to my data analytics portfolio, 
where I showcase my expertise in transforming raw data into actionable insights. 
With skills in Python, R, SQL, Tableau, and more, I specialize in data visualization, statistical analysis, and predictive modeling.
Explore real-world projects and case studies that highlight my ability to uncover trends, solve complex problems, 
and drive data-driven decision-making. Let’s connect to discuss how I can bring value to your next project!]
